### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by JervanSahd** [DexKit/wordpress#1]
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in public_html/wp-content/plugins/dexkit-nft/dexkit-nft.php on line 299

**Comment by JoaoCampos89** [comment]
@JervanSahd I will look at this during the week. I will tag you when done

**Comment by JervanSahd** [comment]
I appreciate it.

**Comment by JoaoCampos89** [comment]
@JervanSahd I pushed a fix to that issue with a new version of the plugin. If issue persists open a new issue, but should work without any issues.
