### ISSUE TITLE
Can´t activate the plugin on wordpress

### ISSUE THREAD

**Issue by markgir** [DexKit/wordpress#2]
Get error;

Fatal error: Can't use function return value in write context in /var/www/bullfin/data/www/dex.bullfinance.online/wp-content/plugins/dexkit-aggregator/dexkit-aggregator.php on line 321

**Comment by JoaoCampos89** [comment]
@markgir I pushed a fix to that issue with a new version of the plugin. If issue persists open a new issue, but should work without any issues.
